### ISSUE TITLE
Running the contributed command:'io-run.run' failed.

### ISSUE THREAD

**Issue by 1noob** [openhoangnc/vscode-io-run#7]
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/31345708/38483259-e1719470-3c04-11e8-902f-ac6f1733bbd1.png">

**Comment by openhoangnc** [comment]
Please add more details:
- OS
- VSCode version
- IORun version
- Full of VScode windows screen shoot
- Full of your souce code
- Installed C/C++ compiler

**Comment by 1noob** [comment]
macOS
<img width="276" alt="image" src="https://user-images.githubusercontent.com/31345708/38486071-8180c3f6-3c0e-11e8-834e-948cd06f76e1.png">
<img width="158" alt="image" src="https://user-images.githubusercontent.com/31345708/38486085-907e97fc-3c0e-11e8-86ee-0800e8d76ee8.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/31345708/38486134-b610d37c-3c0e-11e8-847a-2c70a948af4b.png">
xcode

**Comment by yohgaki** [comment]
I have the same error with php, python and ruby at least. I start observing this error from today after 'dnf update' (OS update). The same error as https://github.com/openhoangnc/vscode-io-run/issues/7#issue-312413183 It was working perfectly before 'dnf update'.
(I cannot tell if VSCode is updated or not, since I did reboot and update. It seems dnf history is not recorded with this)

$ cat /etc/redhat-release
Fedora release 27 (Twenty Seven)

$ rpm -q code
code-1.22.1-1522974574.el7.x86_64

IO Run - v1.0.12

test.php
----
<?php
echo 1234;
----

test.rb
----
p 1234;
----

test.py
----
print(1234)
----

**Comment by openhoangnc** [comment]
Confirmed error happened on Linux with VSCode Version 1.22.1. Will fix soon.
Thank you yohgaki !

**Comment by yohgaki** [comment]
IO Run - v1.0.13 seems fixed this issue. Start working perfectly again. Thanks, that was quick!
